### ISSUE TITLE
CsvHelper.TypeConversion 

### ISSUE THREAD

**Issue by TheMeanerBean** [orbitalteapot/OpenAudible-BookOrganizer#21]
**Describe the bug**
Parsing issues

**To Reproduce**
create books.csv from OpenAudible 4.4.8
run ManagerConsole-linux in ubuntu wsl
./ManagerConsole-linux-x64
OpenAudible Book Manager!
Will make a copy of your audiobooks in a new folder structure based on the metadata in the openaudible export file!
Enter the full path to the source folder containing audio files: /mnt/d/books/
Enter the full path to the openaudible book export file: /mnt/d/books.csv
Enter the full path to the destination folder where you want the organized copy of your audiobooks: /mnt/e/

**Expected behavior**
Start moving and sorting files.

Error returned

Unhandled exception. CsvHelper.TypeConversion.TypeConverterException: The conversion cannot be performed.
    Text: '9/27/2020'
    MemberName: PurchaseDate
    MemberType: System.DateTime
    TypeConverter: 'CsvHelper.TypeConversion.DateTimeConverter'
IReader state:
   ColumnCount: 36
   CurrentIndex: 4
   HeaderRecord:
["Key","Title","Author","Narrated By","Purchase Date","Duration","Release Date","Ave. Rating","Genre","Series Name","Series Sequence","Product ID","ASIN","Book URL","Summary","Description","Rating Count","Publisher","Short Title","Copyright","Author URL","File name","Series URL","Abridged","Language","PDF URL","Image URL","Region","File Paths","AYCE","Read Status","User ID","Position (ms)","Audible (AAX)","Image","M4B"]
IParser state:
   ByteCount: 0
   CharCount: 2886
   Row: 2
   RawRow: 2
   Count: 36
   RawRecord:
BK_ACX0_001175,"Career Diplomacy: Life and Work in the US Foreign Service, 2nd Edition","Harry W. Kopp, Charles A. Gillespie",Wayne Shepherd,9/27/2020,9:38:00,5/14/2012,,Politics & Social Sciences:Politics & Government:International Relations:Diplomacy,,,BK_ACX0_001175,B0082D77F8,https://www.audible.com/pd/B0082D77F8,"<p><i>Career Diplomacy</i> - now in its second edition - is an insider's guide that examines the foreign service as an institution, a profession, and a career. Harry W. Kopp and Charles A. Gillespie, both of whom had long and distinguished careers in the foreign service, provide a full and well-rounded picture of the organization, its place in history, its strengths and weaknesses, and its role in American foreign affairs. Based on their own experiences and through interviews with over 100 current and former foreign service officers and specialists, the authors lay out what to expect in a foreign service career, from the entrance exam through midcareer and into the senior service - how the service works on paper, and in practice. </p> <p>The second edition addresses major changes that have occurred since 2007: the controversial effort to build an expeditionary foreign service to lead the work of stabilization and reconstruction in fragile states; deepening cooperation with the U.S. military and the changing role of the service in Iraq and Afghanistan; the ongoing surge in foreign service recruitment and hiring at the Department of State and U.S. Agency for International Development; and the growing integration of USAID's budget and mission with those of the Department of State. </p> <p>The book is published by Georgetown University Press.</p>","<i>Career Diplomacy</i> - now in its second edition - is an insider's guide that examines the foreign service as an institution, a profession, and a career....",137,University Press Audiobooks,"Career Diplomacy: Life and Work in the US Foreign Service, 2nd Edition",©2011 Georgetown University Press;℗2012 Redwood Audiobooks,https://www.audible.com/author/Harry+W.+Kopp/B002KGRRO4,"Career Diplomacy- Life and Work in the US Foreign Service, 2nd Edition",,FALSE,english,,https://m.media-amazon.com/images/I/61Xs0K--n7L._SL500_.jpg,US,,FALSE,Finished,amzn1.account.AESYFSCRQYSNMUJ3KAB4HAMBSRQQ,,"D:\aax\Career Diplomacy- Life and Work in the US Foreign Service, 2nd Edition.AAX","D:\art\Career Diplomacy- Life and Work in the US Foreign Service, 2nd Edition.jpg","D:\books\Career Diplomacy- Life and Work in the US Foreign Service, 2nd Edition.m4b"

   at CsvHelper.TypeConversion.DefaultTypeConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData)
   at CsvHelper.TypeConversion.DateTimeConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData)
   at lambda_method11(Closure)
   at CsvHelper.Expressions.RecordCreator.Create[T]()
   at CsvHelper.Expressions.RecordManager.Create[T]()
   at CsvHelper.CsvReader.GetRecordsAsync[T](CancellationToken cancellationToken)+MoveNext()
   at CsvHelper.CsvReader.GetRecordsAsync[T](CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:line 27
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:line 27
   at AudioFileSorter.CsvParser.ParseDataCsv(String fullPath, CancellationToken token)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
Aborted (core dumped)

**Additional context**

**Comment by orbitalteapot** [comment]
This issue should be resolved in version 2.0.3, sorry for the delay.

**Comment by TheMeanerBean** [comment]
Unless i am doing something wrong i am still getting the parsing issues with 2.0.2, Would you like the error output? Also is there a link i could buy you a coffee or beer?
[Parsing_error.txt](https://github.com/user-attachments/files/18307815/Parsing_error.txt)
[books.csv](https://github.com/user-attachments/files/18307817/books.csv)

**Comment by orbitalteapot** [comment]
I will have a look, it looks like a date conversation issue :)

**Comment by TheMeanerBean** [comment]
I looks like it was with two books in my list I removed them from csv and its doing its thing now

**Comment by orbitalteapot** [comment]
Thanks for the detailed feedback, hope to have a fix out by tomorrow afternoon

**Comment by orbitalteapot** [comment]
Made a release for you to test: https://github.com/orbitalteapot/OpenAudible-BookOrganizer/releases/tag/2.0.2-bugfix.

**Comment by TheMeanerBean** [comment]
> Made a release for you to test: https://github.com/orbitalteapot/OpenAudible-BookOrganizer/releases/tag/2.0.2-bugfix. @TheMeanerBean

Works like a charm thank you a ton!
